# https://adventofcode.com/2024/day/23

# uiua v0.15.0-dev.1

&fras"example.txt"
regex"(..)-(..)"
# ↙5

▽⊸≡(/↥⌕@t°□⊢)

≡↘₁
∵°□
↙3
# ⊂⊸≡⇌
⍆

# ∧(insert°⊟?) :[]
∧(⍜(?0 0get?⊙:)(insert) °⊟?) :[]

# ⧻

# ok, det finns så klart dublettnycklar i tabellen.
# (och ännu mer så om man även vänder på den)
# så hashtabellen funkar inte med mindre än att låt value vara en array
# ja, så får det bli. börjar med att prova det.
