[package]
name = "day-xx"
version = "0.0.0"
edition = "2021"

[dependencies]
anyhow = "1.0.66"
chrono = "0.4.23"
itertools = "0.10.5"
lazy_static = "1.4.0"
regex = "1.7.0"

[dev-dependencies]
pretty_assertions = "1.3.0"
