# https://adventofcode.com/2021/day/20

# uiua v0.15.0-dev.1
# Experimental!

# img algo ? data
🗄 ← ∩⌞=@# ⊜∘⊸≠@\n :°$"_\n\n_"

# img ? fill img algo
RunAlgo ← ⊏⬚∘⧈(°⋯⇌♭):3_3

# num ? iters img algo
Solve ← ⊙◌ /+♭ ⍥(∧⊸RunAlgo ⨬(0_0|0_1)⊡₀,) ÷₂

🐪 ← Solve 2 🗄
┌─╴🧪
  ⍤⤙≍ 35 🐪 &fras"example.txt"
  ⍤⤙≍ 4873 🐪 &fras"input.txt"
└─╴

🐫 ← Solve 50 🗄
┌─╴🧪
  ⍤⤙≍ 3351 🐫 &fras"example.txt"
  ⍤⤙≍ 16394 🐫 &fras"input.txt"
└─╴
