[package]
name = "day-05"
version = "0.0.0"
edition = "2021"

[dependencies]
itertools = "0.10.5"

[dev-dependencies]
criterion = "0.4.0"
pretty_assertions = "1.3.0"

[[bench]]
name = "bench"
harness = false

[lib]
bench = false
