[package]
name = "day-13"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.71"
colored = "2.0.1"
intcode-computer = { path = "../intcode-computer" }
itertools = "0.11.0"
tui = "0.19.0"

[dev-dependencies]
pretty_assertions = "1.3.0"
